[package]
name        = "ods-lang-rust"
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true
license.workspace     = true
repository.workspace  = true
publish               = false

[dependencies]
ods-core  = { workspace = true }
ods-lang  = { workspace = true }
ods-exec  = { workspace = true }
anyhow    = { workspace = true }
thiserror = { workspace = true }
serde     = { workspace = true }
serde_json = { workspace = true }
tracing   = { workspace = true }
time      = { workspace = true }
regex     = { workspace = true }
walkdir   = { workspace = true }
similar   = { workspace = true }
tokio     = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
