"""
bench.py -- run every security detector against the labelled samples.

    python -m security.bench                 # all detectors
    python -m security.bench phishing_email  # one or more detectors
    python -m security.bench --runs 3        # repeat to check answer stability

Reports per-detector accuracy, errors on the hard negatives, latency and cost,
prints every miss, and writes security/results.json + security/RESULTS.md.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from cli import _load_dotenv
from jev import Jev

from .detectors import ALL, run
from .samples import SAMPLES

HERE = Path(__file__).parent
PRICE_PER_M_INPUT = 0.042  # USD, output tokens are free


def _one(client, det, expected, state, note):
    t0 = time.time()
    try:
        (label, detail), resp = run(client, det, state)
        return {"detector": det.name, "expected": expected, "got": label, "ok": label == expected,
                "hard_negative": note.startswith("HARD NEG"), "note": note, "detail": detail,
                "latency_ms": resp.latency_ms, "input_tokens": resp.usage.get("input_tokens", 0),
                "model": resp.model}
    except Exception as e:  # keep the benchmark going; report the failure
        return {"detector": det.name, "expected": expected, "got": f"ERROR: {e}", "ok": False,
                "hard_negative": note.startswith("HARD NEG"), "note": note, "detail": {},
                "latency_ms": (time.time() - t0) * 1000, "input_tokens": 0, "model": ""}


def main(argv) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("detectors", nargs="*", help=f"subset of: {', '.join(ALL)}")
    ap.add_argument("--runs", type=int, default=1, help="repeat each sample N times")
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args(argv)

    _load_dotenv()
    client = Jev()
    names = args.detectors or list(ALL)
    unknown = [n for n in names if n not in ALL]
    if unknown:
        ap.error(f"unknown detector(s): {unknown}")

    jobs = [(ALL[n], exp, st, note) for n in names for exp, st, note in SAMPLES[n] for _ in range(args.runs)]
    with ThreadPoolExecutor(args.workers) as pool:
        results = list(pool.map(lambda j: _one(client, *j), jobs))

    rows, total_ok, total = [], 0, 0
    for n in names:
        rs = [r for r in results if r["detector"] == n]
        ok = sum(r["ok"] for r in rs)
        hn = [r for r in rs if r["hard_negative"]]
        lat = sorted(r["latency_ms"] for r in rs)
        rows.append({
            "detector": n, "maps_to": ALL[n].maps_to, "n": len(rs), "correct": ok,
            "accuracy": ok / len(rs),
            "hard_neg": f"{sum(r['ok'] for r in hn)}/{len(hn)}" if hn else "-",
            "p50_ms": statistics.median(lat), "max_ms": lat[-1],
            "avg_tokens": statistics.mean(r["input_tokens"] for r in rs),
        })
        total_ok += ok
        total += len(rs)

    tokens = sum(r["input_tokens"] for r in results)
    all_lat = sorted(r["latency_ms"] for r in results)
    model = next((r["model"] for r in results if r["model"]), "?")

    # ---- console ----------------------------------------------------------
    print(f"\nmodel {model}   {total} calls   {tokens:,} input tokens   "
          f"cost ${tokens / 1e6 * PRICE_PER_M_INPUT:.5f}\n")
    print(f"{'detector':<18}{'acc':>8}{'hard-neg':>10}{'p50 ms':>9}{'max ms':>9}{'tok/call':>10}")
    for r in rows:
        print(f"{r['detector']:<18}{r['correct']:>3}/{r['n']:<4}{r['hard_neg']:>10}"
              f"{r['p50_ms']:>9.0f}{r['max_ms']:>9.0f}{r['avg_tokens']:>10.0f}")
    print(f"{'TOTAL':<18}{total_ok:>3}/{total:<4}{'':>10}{statistics.median(all_lat):>9.0f}{all_lat[-1]:>9.0f}")

    misses = [r for r in results if not r["ok"]]
    if misses:
        print("\nMisses:")
        for r in misses:
            print(f"  [{r['detector']}] expected {r['expected']!r} got {r['got']!r}  ({r['note']})  {r['detail']}")

    # ---- files ------------------------------------------------------------
    (HERE / "results.json").write_text(json.dumps({"model": model, "summary": rows, "results": results}, indent=2))
    md = [f"# Security benchmark results\n",
          f"Model `{model}` · {total} calls · {tokens:,} input tokens · "
          f"${tokens / 1e6 * PRICE_PER_M_INPUT:.5f} total · median latency {statistics.median(all_lat):.0f} ms\n",
          "Generated by `python -m security.bench`. Samples are hand-written (see `samples.py`); "
          "this is a smoke test of fit, not a statistically meaningful evaluation.\n",
          "| Detector | Maps to | Correct | Hard negatives | p50 ms | max ms |",
          "|---|---|---|---|---|---|"]
    for r in rows:
        md.append(f"| `{r['detector']}` | {r['maps_to']} | {r['correct']}/{r['n']} | {r['hard_neg']} | "
                  f"{r['p50_ms']:.0f} | {r['max_ms']:.0f} |")
    md.append(f"| **Total** | | **{total_ok}/{total}** ({total_ok / total:.0%}) | | "
              f"{statistics.median(all_lat):.0f} | {all_lat[-1]:.0f} |\n")
    if misses:
        md += ["## Misses\n", "| Detector | Expected | Got | Sample | Detail |", "|---|---|---|---|---|"]
        for r in misses:
            md.append(f"| `{r['detector']}` | {r['expected']} | {r['got']} | {r['note']} | `{json.dumps(r['detail'])}` |")
    (HERE / "RESULTS.md").write_text("\n".join(md) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
