"""Prepare OpenLLaMA-3B for the CODA-rs CUDA backend.

`prepare` : download OpenLLaMA-3B, convert its weights into the flat layout the
            Rust `coda-llm` binary expects, tokenize a generation prompt, and
            save reference last-token logits (a real HuggingFace forward) so the
            Rust forward can be verified against it.
`decode`  : turn the token ids `coda-llm` generated back into text.

The CODA backend implements the LLaMA architecture directly, so the only work
here is a layout conversion:
  * q/k/v projections are concatenated into one fused `wqkv`;
  * gate/up projections are interleaved into one `wgu` (SwiGLU expects adjacent
    gate/value lanes);
  * q/k are *un-permuted* from HuggingFace's rotate-half RoPE convention back to
    the adjacent-pair convention the CODA `k_rope` kernel uses;
  * PyTorch `[out, in]` Linear weights are transposed to the `[in, out]` matmul
    layout, and everything is written as fp32.
"""

import struct
import sys

import numpy as np

MODEL = "openlm-research/open_llama_3b_v2"
WORK = "/work"
GEN_PROMPT = "The history of computing began"
VER_PROMPT = "The capital of France is"
MAGIC = 0x41444F43  # 'CODA'


def unpermute(w, n_heads, head_dim, hidden):
    """HuggingFace rotate-half RoPE layout -> adjacent-pair (Meta) layout."""
    return (
        w.reshape(n_heads, 2, head_dim // 2, hidden)
        .transpose(0, 2, 1, 3)
        .reshape(n_heads * head_dim, hidden)
    )


def prepare():
    import torch
    from transformers import LlamaForCausalLM, LlamaTokenizer

    tok = LlamaTokenizer.from_pretrained(MODEL)
    model = LlamaForCausalLM.from_pretrained(MODEL, torch_dtype=torch.float32)
    model.eval()
    cfg = model.config
    d, nl = cfg.hidden_size, cfg.num_hidden_layers
    nh = cfg.num_attention_heads
    hd = d // nh
    dff, vocab = cfg.intermediate_size, cfg.vocab_size
    eps = float(cfg.rms_norm_eps)
    rope_base = float(getattr(cfg, "rope_theta", 10000.0))
    print(f"prepared: d={d} nl={nl} nh={nh} hd={hd} dff={dff} vocab={vocab}", flush=True)

    sd = model.state_dict()
    g = lambda k: sd[k].detach().numpy().astype(np.float32)

    with open(f"{WORK}/model.bin", "wb") as out:
        out.write(struct.pack("<7I2f", MAGIC, vocab, d, nl, nh, hd, dff, eps, rope_base))

        def wt(arr):
            out.write(np.ascontiguousarray(arr, dtype=np.float32).tobytes())

        wt(g("model.embed_tokens.weight"))  # embed [vocab, d]
        for i in range(nl):
            p = f"model.layers.{i}."
            wt(g(p + "input_layernorm.weight"))  # gamma_attn [d]
            q = unpermute(g(p + "self_attn.q_proj.weight"), nh, hd, d)
            k = unpermute(g(p + "self_attn.k_proj.weight"), nh, hd, d)
            v = g(p + "self_attn.v_proj.weight")
            wt(np.concatenate([q.T, k.T, v.T], axis=1))  # wqkv [d, 3d]
            wt(g(p + "self_attn.o_proj.weight").T)  # wo [d, d]
            wt(g(p + "post_attention_layernorm.weight"))  # gamma_ffn [d]
            gate = g(p + "mlp.gate_proj.weight").T  # [d, dff]
            up = g(p + "mlp.up_proj.weight").T  # [d, dff]
            wgu = np.empty((d, 2 * dff), dtype=np.float32)
            wgu[:, 0::2] = gate
            wgu[:, 1::2] = up
            wt(wgu)  # wgu [d, 2*dff]
            wt(g(p + "mlp.down_proj.weight").T)  # wdown [dff, d]
        wt(g("model.norm.weight"))  # gamma_final [d]
        lm = "lm_head.weight" if "lm_head.weight" in sd else "model.embed_tokens.weight"
        wt(g(lm).T)  # lm_head [d, vocab]

    gen_ids = tok(GEN_PROMPT)["input_ids"]
    ver_ids = tok(VER_PROMPT)["input_ids"]
    with open(f"{WORK}/gen_ids.txt", "w") as f:
        f.write(" ".join(map(str, gen_ids)))
    with open(f"{WORK}/ver_ids.txt", "w") as f:
        f.write(" ".join(map(str, ver_ids)))

    # Reference last-token logits from a genuine HuggingFace forward.
    with torch.no_grad():
        ref = model(torch.tensor([ver_ids])).logits[0, -1, :].numpy().astype(np.float32)
    ref.tofile(f"{WORK}/ref_logits.bin")
    print(f"verify prompt: {VER_PROMPT!r}  HF argmax token = {int(ref.argmax())}", flush=True)


def decode():
    from transformers import LlamaTokenizer

    tok = LlamaTokenizer.from_pretrained(MODEL)
    ids = list(map(int, open(f"{WORK}/out_ids.txt").read().split()))
    print("\n=== text generated by the CODA-rs CUDA backend ===\n")
    print(tok.decode(ids))
    print("\n=== end ===", flush=True)


if __name__ == "__main__":
    {"prepare": prepare, "decode": decode}[sys.argv[1]]()
