#!/usr/bin/env python3
"""
Auto-optimization hook — runs after each turn to detect waste
patterns and write rules to .claude/rules/token-optimization.md.

Never touches the user's CLAUDE.md. Rules go to a dedicated file
that Claude Code auto-loads from .claude/rules/.

Usage as Stop hook:
  python3 <toolkit-dir>/auto_optimize.py
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

RULES_FILENAME = "token-optimization.md"
LAST_RUN = Path("/tmp/.auto_optimize_last")
MIN_INTERVAL_SECS = 300


def find_project_root() -> Path | None:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            return Path(result.stdout.strip())
    except (subprocess.TimeoutExpired, OSError):
        pass
    cwd = Path.cwd()
    if (cwd / ".claude").exists() or (cwd / "CLAUDE.md").exists():
        return cwd
    return None


def find_session_jsonl() -> Path | None:
    claude_dir = Path.home() / ".claude" / "projects"
    if not claude_dir.exists():
        return None
    candidates = []
    for jsonl in claude_dir.rglob("*.jsonl"):
        candidates.append((jsonl.stat().st_mtime, jsonl))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def should_run() -> bool:
    if not LAST_RUN.exists():
        return True
    try:
        last = float(LAST_RUN.read_text().strip())
        return (time.time() - last) > MIN_INTERVAL_SECS
    except (ValueError, OSError):
        return True


def run_optimizer(jsonl_path: Path):
    sys.path.insert(0, str(Path(__file__).parent))
    from optimizer import analyze_session
    return analyze_session(str(jsonl_path))


def format_rules(rules) -> str:
    severity_map = {1: "HIGH", 2: "MED", 3: "LOW"}
    lines = [
        "# Token Optimization Rules",
        "",
        f"# Auto-generated by token-flamegraph (updated {time.strftime('%Y-%m-%d %H:%M:%S')})",
        "# This file is managed automatically. Edit freely — your changes",
        "# will be preserved in a future version, or delete this file to",
        "# disable auto-generated rules.",
        "",
    ]
    for rule in rules:
        sev = severity_map.get(rule.priority, "LOW")
        lines.append(f"## [{sev}] {rule.title}")
        lines.append(f"# Saves ~{rule.estimated_savings_pct:.0f}% — {rule.evidence}")
        lines.append(rule.claude_md_directive)
        lines.append("")
    return "\n".join(lines)


def rules_changed(old_content: str, new_rules) -> bool:
    old_titles = set()
    for line in old_content.split("\n"):
        if line.startswith("## ["):
            old_titles.add(line.split("] ", 1)[-1] if "] " in line else line)
    new_titles = {r.title for r in new_rules}
    return old_titles != new_titles


def main():
    if not should_run():
        return

    jsonl = find_session_jsonl()
    if not jsonl:
        return

    try:
        rules = run_optimizer(jsonl)
    except Exception:
        return

    if not rules:
        return

    LAST_RUN.write_text(str(time.time()))

    project_root = find_project_root()
    if not project_root:
        return

    rules_dir = project_root / ".claude" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    rules_file = rules_dir / RULES_FILENAME

    old_content = rules_file.read_text() if rules_file.exists() else ""

    if rules_changed(old_content, rules):
        rules_file.write_text(format_rules(rules))
        count = len(rules)
        top = rules[0].title if rules else ""
        print(f"📊 .claude/rules/{RULES_FILENAME} updated: {count} rules (top: {top})")


if __name__ == "__main__":
    main()
