//! Embed the hand-authored recipe corpus (`recipes/seed/*.yaml` +
//! `recipes/antipatterns/*.yaml`) into the static binary via
//! `include_str!`. Runs at build-time; emits a `bundled_recipes.rs` file
//! that `store.rs` `include!`s.
//!
//! Why: the product's flywheel depends on a cross-repo recipe corpus
//! at `~/.ods/recipes.db`. On first-open of an empty global store we
//! want to bootstrap with the shipped seeds without requiring the user
//! to run `ods recipes import-dir recipes/seed` — and without requiring
//! the source tree to be available at runtime (it isn't, for a musl
//! single-binary deploy).

use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let crate_root = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by cargo");
    // Workspace root is two levels up from `crates/ods-recipes/`.
    let workspace_root = Path::new(&crate_root).join("..").join("..");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let out_path = Path::new(&out_dir).join("bundled_recipes.rs");
    let mut f = fs::File::create(&out_path).expect("create bundled_recipes.rs");

    writeln!(
        f,
        "/// Compile-time corpus: (filename, YAML content) for every recipe under\n\
         /// `recipes/seed/` and `recipes/antipatterns/`. Regenerated by build.rs on\n\
         /// every build (cargo:rerun-if-changed below).\n\
         pub const BUNDLED_RECIPES: &[(&str, &str)] = &["
    )
    .unwrap();

    for subdir in &["recipes/seed", "recipes/antipatterns"] {
        let dir = workspace_root.join(subdir);
        println!("cargo:rerun-if-changed={}", dir.display());
        let Ok(entries) = fs::read_dir(&dir) else {
            // Directory absent in some CI layouts (e.g. published crate); skip.
            continue;
        };
        let mut entries: Vec<_> = entries.filter_map(|e| e.ok()).collect();
        entries.sort_by_key(|e| e.file_name());
        for entry in entries {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("yaml") {
                continue;
            }
            let name = path
                .file_name()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_else(|| "unknown".into());
            // Canonicalise so `include_str!` accepts the path regardless of
            // where cargo invokes us from (workspace build vs. crate build).
            let abs = path.canonicalize().expect("canonicalize recipe path");
            writeln!(
                f,
                "    ({:?}, include_str!({:?})),",
                name,
                abs.to_string_lossy().as_ref()
            )
            .unwrap();
        }
    }

    writeln!(f, "];").unwrap();
}
