[package]
name        = "ods-recipes"
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true
license.workspace     = true
repository.workspace  = true
publish               = false
build                 = "build.rs"

[dependencies]
ods-core   = { workspace = true }
anyhow     = { workspace = true }
thiserror  = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tracing    = { workspace = true }
rusqlite   = { workspace = true }
sqlite-vec = "=0.1.8"
time       = { workspace = true }

[dev-dependencies]
criterion = "0.5"
tempfile  = { workspace = true }

[[bench]]
name    = "score_bench"
harness = false
