"""
Export — bundle compiled artifacts into a shareable, self-contained file.

The "compiled outputs which can be shared externally" requirement. Produces a
single standalone HTML file (no external assets, no JS) containing every
artifact plus its provenance from the build cache, so it can be emailed,
dropped in a wiki, or published as-is. Pure stdlib — no dependencies.
"""

from __future__ import annotations

import html
from pathlib import Path

from .cache import Cache
from .spec import Workflow

_CSS = """
body{font:16px/1.6 -apple-system,Segoe UI,Roboto,sans-serif;max-width:820px;
margin:2rem auto;padding:0 1rem;color:#1a1a1a}
h1{border-bottom:2px solid #eee;padding-bottom:.3rem}
.artifact{border:1px solid #e3e3e3;border-radius:8px;margin:1.5rem 0;overflow:hidden}
.artifact>h2{margin:0;padding:.6rem 1rem;background:#f6f8fa;border-bottom:1px solid #e3e3e3;font-size:1.1rem}
.meta{font-size:.8rem;color:#666;padding:.4rem 1rem;background:#fafbfc;border-bottom:1px solid #eee}
.meta code{background:#eef;padding:.05rem .3rem;border-radius:3px}
.body{padding:1rem;white-space:pre-wrap;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.9rem}
footer{margin-top:3rem;color:#999;font-size:.8rem;text-align:center}
"""


def export_html(wf: Workflow, out_path: str | Path) -> Path:
    """Render all built artifacts into one shareable HTML file."""
    cache = Cache(wf.cache_path)
    parts = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        f"<title>{html.escape(wf.project)} — llmake build</title>",
        f"<style>{_CSS}</style></head><body>",
        f"<h1>{html.escape(wf.project)}</h1>",
        "<p>Compiled inference results, exported by "
        "<strong>llmake</strong>.</p>",
    ]

    if not cache.entries:
        parts.append("<p><em>No artifacts built yet. Run "
                     "<code>llmake build</code> first.</em></p>")

    for name, entry in cache.entries.items():
        artifact = wf.root / entry.artifact
        body = artifact.read_text() if artifact.is_file() else "(artifact missing)"
        meta = (
            f"provider <code>{html.escape(entry.provider)}</code> · "
            f"model <code>{html.escape(entry.model or '—')}</code> · "
            f"built {html.escape(entry.created)} · "
            f"inputs: {html.escape(', '.join(entry.inputs) or '—')}"
        )
        parts += [
            "<div class='artifact'>",
            f"<h2>{html.escape(name)}</h2>",
            f"<div class='meta'>{meta}</div>",
            f"<div class='body'>{html.escape(body)}</div>",
            "</div>",
        ]

    parts.append(
        f"<footer>{html.escape(wf.project)} · {len(cache.entries)} artifact(s) · "
        "generated by llmake</footer></body></html>"
    )

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts))
    return out
